<a href="https://colab.research.google.com/github/VegaSera/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/module2-backpropagation/LS_DS_432_Backprop_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Using TensorFlow Keras, Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn.

This is your "Hello World!" of TensorFlow.

### Example TensorFlow Starter Code

```python 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(3, activation='sigmoid', input_dim=2),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['acc'])

results = model.fit(X,y, epochs=100)

```

### Additional Written Tasks:
1. Investigate the various [loss functions](https://www.tensorflow.org/api_docs/python/tf/keras/losses). Which is best suited for the task at hand (predicting 1 / 0) and why? 
* Considering it's a binary classification problem, the best loss function for this problem is likely BinaryCrossentropy
2. What is the difference between a loss function and a metric? Why might we need both in Keras? 
3. Investigate the various [optimizers](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers). Stochastic Gradient Descent (`sgd`) is not the learning algorithm dejour anyone. Why is that? What do newer optimizers such as `adam` have to offer? 

In [1]:
import pandas as pd
data_xor = {'X1': [0, 0, 1, 0, 1, 1, 0], 'X2': [0, 1, 0, 1, 0, 1, 0], 'X3': [1, 1, 1, 0, 0, 1, 0], 'output': [0, 1, 1, 1, 1, 0, 0]}
df = pd.DataFrame.from_dict(data_xor)
X = df[['X1', 'X2', 'X3']].values
y = df['output'].values
print(X)
print(y)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
[0 1 1 1 1 0 0]


In [2]:
##### Your Code Here #####
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
 
model = Sequential([
    Dense(4, activation='sigmoid', input_dim=3),
    Dense(1, activation='sigmoid')
])
 
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['acc'])
 
results = model.fit(X,y, epochs=100)
 


Epoch 1/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6872 - acc: 0.5714
Epoch 2/100
1/1 [==============================] - 0s 986us/step - loss: 0.6871 - acc: 0.5714
Epoch 3/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6870 - acc: 0.5714
Epoch 4/100
1/1 [==============================] - 0s 1ms/step - loss: 0.6869 - acc: 0.5714
Epoch 5/100
1/1 [==============================] - 0s 1ms/step - loss: 0.6867 - acc: 0.5714
Epoch 6/100
1/1 [==============================] - 0s 1ms/step - loss: 0.6866 - acc: 0.5714
Epoch 7/100
1/1 [==============================] - 0s 994us/step - loss: 0.6865 - acc: 0.5714
Epoch 8/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6864 - acc: 0.5714
Epoch 9/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6863 - acc: 0.5714
Epoch 10/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6861 - acc: 0.5714
Epoch 11/100
1/1 [==============================] - 0s 2ms/step - loss: 0.6

In [3]:
scores = model.evaluate(X, y)
print(f"{model.metrics_names[1]}: {scores[1]*100}")

1/1 [==============================] - 0s 1ms/step - loss: 0.6791 - acc: 0.5714
acc: 57.14285969734192


### Build a Tensor Keras Perceptron

Try to match the architecture we used on Monday - inputs nodes and one output node. Apply this architecture to the XOR-ish dataset above. 

After fitting your model answer these questions: 

Are you able to achieve the same results as a bigger architecture from the first part of the assignment? Why is this disparity the case? What properties of the XOR dataset would cause this disparity? 

Now extrapolate this behavior on a much larger dataset in terms of features. What kind of architecture decisions could we make to avoid the problems the XOR dataset presents at scale? 

*Note:* The bias term is baked in by default in the Dense layer.

In [4]:
model2 = Sequential([
    Dense(1, activation='sigmoid', input_dim=3),
])
 
model2.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['acc'])
 
results = model2.fit(X,y, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 1ms/step - loss: 0.7322 - acc: 0.5714
Epoch 2/100
1/1 [==============================] - 0s 3ms/step - loss: 0.7316 - acc: 0.4286
Epoch 3/100
1/1 [==============================] - 0s 2ms/step - loss: 0.7309 - acc: 0.4286
Epoch 4/100
1/1 [==============================] - 0s 1ms/step - loss: 0.7303 - acc: 0.4286
Epoch 5/100
1/1 [==============================] - 0s 1ms/step - loss: 0.7296 - acc: 0.4286
Epoch 6/100
1/1 [==============================] - 0s 2ms/step - loss: 0.7290 - acc: 0.4286
Epoch 7/100
1/1 [==============================] - 0s 1ms/step - loss: 0.7283 - acc: 0.4286
Epoch 8/100
1/1 [==============================] - 0s 1ms/step - loss: 0.7277 - acc: 0.4286
Epoch 9/100
1/1 [==============================] - 0s 1ms/step - loss: 0.7271 - acc: 0.4286
Epoch 10/100
1/1 [==============================] - 0s 1ms/step - loss: 0.7264 - acc: 0.4286
Epoch 11/100
1/1 [==============================] - 0s 2ms/step - loss: 0.7258 

In [5]:
scores2 = model2.evaluate(X, y)
print(f"{model2.metrics_names[1]}: {scores2[1]*100}")

1/1 [==============================] - 0s 1ms/step - loss: 0.6864 - acc: 0.4286
acc: 42.85714328289032


## Try building/training a more complex MLP on a bigger dataset.

Use TensorFlow Keras & the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the canonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the Internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


### Parts
1. Gathering & Transforming the Data
2. Making MNIST a Binary Problem
3. Estimating your Neural Network (the part you focus on)

### Gathering the Data 

`keras` has a handy method to pull the mnist dataset for you. You'll notice that each observation is a 28x28 arrary which represents an image. Although most Neural Network frameworks can handle higher dimensional data, that is more overhead than necessary for us. We need to flatten the image to one long row which will be 784 values (28X28). Basically, you will be appending each row to one another to make on really long row. 

In [0]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [0]:
# input image dimensions
img_rows, img_cols = 28, 28

In [0]:
# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [0]:
x_train = x_train.reshape(x_train.shape[0], img_rows * img_cols)
x_test = x_test.reshape(x_test.shape[0], img_rows * img_cols)

# Normalize Our Data
x_train = x_train / 255
x_test = x_test / 255

In [10]:
# Now the data should be in a format you're more familiar with
x_train.shape

(60000, 784)

### Making MNIST a Binary Problem 
MNIST is multiclass classification problem; however we haven't covered all the necessary techniques to handle this yet. You would need to one-hot encode the target, use a different loss metric, and use softmax activations for the last layer. This is all stuff we'll cover later this week, but let us simplify the problem for now: Zero or all else.

In [0]:
import numpy as np

y_temp = np.zeros(y_train.shape)
y_temp[np.where(y_train == 0.0)[0]] = 1
y_train = y_temp

y_temp = np.zeros(y_test.shape)
y_temp[np.where(y_test == 0.0)[0]] = 1
y_test = y_temp

In [12]:
# A Nice Binary target for ya to work with
y_train

array([0., 1., 0., ..., 0., 0., 0.])

### Estimating Your `net

**The hardest portion of this assignment is following the Numpy shapes in the backprop function**



In [0]:
##### Your Code Here #####

class NeuralNetwork:
    def __init__(self):
        # Set up Architecture of Neural Network
        self.inputs = 784
        self.hiddenNodes = 128
        self.outputNodes = 1

        # Initial Weights
        # 3x3 Matrix Array for the First Layer
        self.weights1 = np.random.rand(self.inputs, self.hiddenNodes)
       
        # 3x1 Matrix Array for Hidden to Output
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forward.
        aka "predict"
        """
        
        # Weighted sum of inputs => hidden layer
        self.hidden_sum = np.dot(X, self.weights1)
        
        # Activations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weight sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Final activation of output
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
        
    def backward(self, X,y,o):
        """
        Backward propagate through the network
        """
        
        # Error in Output
        # Categorical Cross Entropy - Would a function to do this. 
        self.o_error = y - o
        
        # Apply Derivative of Sigmoid to error
        # How far off are we in relation to the Sigmoid f(x) of the output
        # ^- aka hidden => output
        self.o_delta = self.o_error * self.sigmoidPrime(o)
        
        # z2 error
        self.o_delta = np.expand_dims(self.o_delta, axis=1)
        self.z2_error = self.o_delta * self.weights2.T
        
        # How much of that "far off" can explained by the input => hidden
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        
        # Adjustment to first set of weights (input => hidden)
        self.weights1 += X.T.dot(self.z2_delta)
        # Adjustment to second set of weights (hidden => output)
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)
        

    def train(self, X, y):
        o = self.feed_forward(X)[:,0]
        self.backward(X,y,o)

In [21]:
nn = NeuralNetwork()
nn.train(x_train, y_train)

nn.o_error.shape 

(60000,)

In [16]:
t = nn.o_error * nn.sigmoidPrime(nn.feed_forward(x_test[:500]))
t.shape

(500, 60000)

In [22]:
nn = NeuralNetwork()

# Number of Epochs / Iterations
for i in range(10000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 1000 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print("Loss: \n", str(np.mean(np.square(y_test- nn.feed_forward(x_test)))))
    nn.train(x_train[:500],y_train[:500])

+---------EPOCH 1---------+
Loss: 
 0.902
+---------EPOCH 2---------+
Loss: 
 0.902
+---------EPOCH 3---------+
Loss: 
 0.902
+---------EPOCH 4---------+
Loss: 
 0.902
+---------EPOCH 5---------+
Loss: 
 0.902
+---------EPOCH 1000---------+
Loss: 
 0.902
+---------EPOCH 2000---------+
Loss: 
 0.902
+---------EPOCH 3000---------+
Loss: 
 0.902
+---------EPOCH 4000---------+
Loss: 
 0.902
+---------EPOCH 5000---------+
Loss: 
 0.902
+---------EPOCH 6000---------+
Loss: 
 0.902
+---------EPOCH 7000---------+
Loss: 
 0.902
+---------EPOCH 8000---------+
Loss: 
 0.902
+---------EPOCH 9000---------+
Loss: 
 0.902
+---------EPOCH 10000---------+
Loss: 
 0.902


In [27]:
#Didn't really understand the purpose of the neural network class above since we were told to use TensorFlow and Keras to do this part...
model = Sequential([
    Dense(1, activation='sigmoid', input_dim=784)
])
 
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['acc'])
 
results = model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1068 - acc: 0.9716
Epoch 2/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0586 - acc: 0.9852
Epoch 3/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0501 - acc: 0.9872
Epoch 4/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0458 - acc: 0.9880
Epoch 5/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0430 - acc: 0.9886
Epoch 6/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0410 - acc: 0.9890
Epoch 7/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0395 - acc: 0.9894
Epoch 8/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0384 - acc: 0.9895
Epoch 9/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0374 - acc: 0.9898
Epoch 10/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0366 - acc: 0.9900


## Stretch Goals: 

- Make MNIST a multiclass problem using cross entropy & soft-max
- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?